services:
  backend:
    build:
      context: ./Synapse_api
      dockerfile: Dockerfile
    container_name: synapse_api
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - ./Synapse_api/.env
    environment:
      - NODE_ENV=production
      - PORT=4000
    networks:
      - synapse_network

  frontend:
    build:
      context: ./synapse_web
      dockerfile: Dockerfile
    container_name: synapse_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./synapse_web/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_BACKEND_URL=http://backend:4000/api
    depends_on:
      - backend
    networks:
      - synapse_network

networks:
  synapse_network:
    driver: bridge